---
collections:
  - name: ansible.netcommon
  - name: ansible.utils
  - name: cisco.ios
  - name: https://github.com/redhat-cop/network.base
    type: git
    version: devel
  - name: https://github.com/redhat-cop/network.bgp
    type: git
    version: devel
