---
- hosts: rtr1
  gather_facts: false
  tasks:
    - name: Network BGP Manager
      ansible.builtin.include_role:
        name: network.bgp.run
      vars:
        ansible_network_os: cisco.ios.ios
        actions:
          - name: persist
