---
- hosts: rtr1
  gather_facts: false
  tasks:
    - name: Network BGP Manager
      ansible.builtin.include_role:
        name: network.base.resource_manager
      vars:
        action: persist
        resources:
          - 'interfaces'
          - 'l2_interfaces'
          - 'l3_interfaces'
